// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suhubitukuoonpiqsgtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aHViaXR1a3Vvb25waXFzZ3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTE5MzIsImV4cCI6MjA2Nzc4NzkzMn0.epedg4JQ5MehNJ5aY3lwJznM_9m50Gq-RHi4UB1aujM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});